version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: eldorado-backend
    environment:
      - SPRING_PROFILES_ACTIVE=prod  
    ports:
      - "40269:8080"
    networks:
      - eldorado-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8080}
    container_name: eldorado-frontend
    ports:
      - "40270:3000"
    depends_on:
      - backend
    networks:
      - eldorado-network

networks:
  eldorado-network:
    driver: bridge